# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c5e7d4addba1c2c294fe07198fc688bf961a3a7dfe59bd6f4c00d3aed7925d4505064af6f2c815d29af2f4b00d5e38f677ee1dbe1bd38efb7cdf09a132be48d

test:
  secret_key_base: 56fef7c3cb0a0411bb538a73ad505826db9bbd1b549b376e04ae71431be6877a00bb837f2c157b9f6da714bb1d5f198c104389ac0a2335c1e218d9361b841623

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
